name: myproject_functions
description: My project functions
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  # Firebase Functions bindings
  firebase_functions_interop: ^0.0.3
  # Node bindings required to compile a nice-looking JS file for Node.
  # Also provides access to globals like `require` and `exports`.
  node_interop: ^0.0.4
  html: ^0.13.3
  meta: ^1.1.2
  tuple: ^1.0.1
  sembast: ^1.7.0

transformers:
  - $dart2js
  - node_interop # This transformer must go after $dart2js
